In [1]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv('Load Data in kW.csv')
data.head()
min_load=data.min()
print(min_load)
max_load=data.max()
print(max_load)

Load (kW)     3377.9196
Unnamed: 3          NaN
Unnamed: 4          NaN
Unnamed: 5          NaN
Unnamed: 6          NaN
Unnamed: 7          NaN
Unnamed: 8          NaN
Unnamed: 9          NaN
dtype: float64
Load (kW)     8841.66948
Unnamed: 3           NaN
Unnamed: 4           NaN
Unnamed: 5           NaN
Unnamed: 6           NaN
Unnamed: 7           NaN
Unnamed: 8           NaN
Unnamed: 9           NaN
dtype: float64


In [14]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()

In [15]:
a=np.zeros((len(data)-72,7))
print(a.shape)

(2112, 7)


In [19]:
from sklearn.model_selection import train_test_split
a,a_test=train_test_split(a,test_size=0.05,random_state=1)
print(a.shape)
print(a_test.shape)
q1=len(a)
print(q1)
q2=len(a_test)
print(q2)

(1905, 7)
(101, 7)
1905
101


In [20]:
weights=np.random.uniform(-1,1,size=(6,1))
print(weights.shape)
print(weights)

(6, 1)
[[ 0.06274413]
 [-0.92403334]
 [-0.3098307 ]
 [-0.66601787]
 [ 0.4890539 ]
 [ 0.38271056]]


In [21]:
l=0.001
for i in range(100):
    for j in range(q1):
        n=np.dot(a[j,0:6],weights)
        o=1/(1+np.exp(-n))
        dw=(l*(a[[j],6]-o))*o*(1-o)*a[[j],0:6].T
        weights=weights+dw
print(dw)
print(weights)

[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
[[ 0.06274413]
 [-0.92403334]
 [-0.3098307 ]
 [-0.66601787]
 [ 0.4890539 ]
 [ 0.38271056]]


In [22]:
o2=np.zeros((q2,1))
for j in range(q2):
    n2=np.dot(a_test[j,0:6],weights)
    o2[j]=1/(1+np.exp(-n2))


In [28]:
c=10
n=np.dot(a[c,0:6],weights)
o=1/(1+np.exp(-n))
Actual_load=a[c,6]*(max_load-min_load)+min_load
Estimated_load=o*(max_load-min_load)+min_load
print('Actual Load=',Actual_load)
print('Estimated Load=',Estimated_load)

Actual Load= Load (kW)     3377.9196
Unnamed: 3          NaN
Unnamed: 4          NaN
Unnamed: 5          NaN
Unnamed: 6          NaN
Unnamed: 7          NaN
Unnamed: 8          NaN
Unnamed: 9          NaN
dtype: float64
Estimated Load= Load (kW)     6109.79454
Unnamed: 3           NaN
Unnamed: 4           NaN
Unnamed: 5           NaN
Unnamed: 6           NaN
Unnamed: 7           NaN
Unnamed: 8           NaN
Unnamed: 9           NaN
dtype: float64
